name:  dy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        User: ${{ github.event.repository.owner.id }}
    steps:

      - name: Checkout
        run: |
          git clone https://github.com/kongjianweimei/18.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
          npm install md5-node
      - name: 'run 【dj】'
        run: |
          cd ~/js
          node Task/djtx.js
      - name: 'run 【tdt】'
        run: |
          cd ~/js
          node Task/tdt.js
